"""Add sale fields

Revision ID: fc3ff8b74ff7
Revises: 0012_add_retailer_contact_info
Create Date: 2026-08-14 07:05:34.893312
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fc3ff8b74ff7'
down_revision = '0012_add_retailer_contact_info'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_canonical_products_barcode', 'canonical_products', type_='unique')
    op.drop_index('ix_canonical_products_barcode', table_name='canonical_products')
    op.create_index(op.f('ix_canonical_products_barcode'), 'canonical_products', ['barcode'], unique=True)
    op.drop_constraint('uq_product_families_name', 'product_families', type_='unique')
    op.drop_index('ix_product_families_name', table_name='product_families')
    op.create_index(op.f('ix_product_families_name'), 'product_families', ['name'], unique=True)
    op.add_column('product_listings', sa.Column('is_on_sale', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('product_listings', sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_listings', sa.Column('promotional_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('product_listings', sa.Column('sale_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('uq_product_listings_source_store_retailer_product', table_name='product_listings', postgresql_where='(retailer_product_id IS NOT NULL)')
    op.create_index(op.f('ix_product_listings_is_on_sale'), 'product_listings', ['is_on_sale'], unique=False)
    op.add_column('product_price_observations', sa.Column('is_on_sale', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('product_price_observations', sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_price_observations', sa.Column('promotional_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.drop_constraint('uq_price_obs_source_location', 'product_price_observations', type_='unique')
    op.drop_constraint('uq_retailer_data_sources_retailer_id_source_url', 'retailer_data_sources', type_='unique')
    op.drop_constraint('uq_retailers_name', 'retailers', type_='unique')
    op.drop_index('ix_retailers_name', table_name='retailers')
    op.create_index(op.f('ix_retailers_name'), 'retailers', ['name'], unique=True)
    op.drop_index('ix_stores_is_active', table_name='stores')
    op.drop_index('ix_stores_needs_review', table_name='stores')
    op.drop_constraint('uq_stores_external_source_external_id', 'stores', type_='unique')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_unique_constraint('uq_stores_external_source_external_id', 'stores', ['external_source', 'external_id'])
    op.create_index('ix_stores_needs_review', 'stores', ['needs_review'], unique=False)
    op.create_index('ix_stores_is_active', 'stores', ['is_active'], unique=False)
    op.drop_index(op.f('ix_retailers_name'), table_name='retailers')
    op.create_index('ix_retailers_name', 'retailers', ['name'], unique=False)
    op.create_unique_constraint('uq_retailers_name', 'retailers', ['name'])
    op.create_unique_constraint('uq_retailer_data_sources_retailer_id_source_url', 'retailer_data_sources', ['retailer_id', 'source_url'])
    op.create_unique_constraint('uq_price_obs_source_location', 'product_price_observations', ['canonical_product_id', 'observed_at', 'source', 'source_url', 'raw_region', 'raw_area', 'raw_store_name'])
    op.drop_column('product_price_observations', 'promotional_tags')
    op.drop_column('product_price_observations', 'regular_price')
    op.drop_column('product_price_observations', 'is_on_sale')
    op.drop_index(op.f('ix_product_listings_is_on_sale'), table_name='product_listings')
    op.create_index('uq_product_listings_source_store_retailer_product', 'product_listings', ['source', 'store_id', 'retailer_product_id'], unique=True, postgresql_where='(retailer_product_id IS NOT NULL)')
    op.drop_column('product_listings', 'sale_ends_at')
    op.drop_column('product_listings', 'promotional_tags')
    op.drop_column('product_listings', 'regular_price')
    op.drop_column('product_listings', 'is_on_sale')
    op.drop_index(op.f('ix_product_families_name'), table_name='product_families')
    op.create_index('ix_product_families_name', 'product_families', ['name'], unique=False)
    op.create_unique_constraint('uq_product_families_name', 'product_families', ['name'])
    op.drop_index(op.f('ix_canonical_products_barcode'), table_name='canonical_products')
    op.create_index('ix_canonical_products_barcode', 'canonical_products', ['barcode'], unique=False)
    op.create_unique_constraint('uq_canonical_products_barcode', 'canonical_products', ['barcode'])
    # ### end Alembic commands ###
